# Generated by Django 6.1.1 on 2026-10-01 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        ('tipos_riesgo', '0001_initial'),
        ('zonas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='tipos_riesgo.tiporiesgo'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='zonas.zona'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='reportes.reporte'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='validacion',
            constraint=models.UniqueConstraint(fields=('reporte', 'usuario'), name='validacion_unica_por_usuario'),
        ),
    ]
