# Generated by Django 6.1.1 on 2026-10-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('nivel', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], default='bajo', max_length=5)),
                ('peso', models.FloatField(default=1.0, help_text='Peso usado para calcular el riesgo de una zona.')),
            ],
            options={
                'verbose_name': 'tipo de riesgo',
                'verbose_name_plural': 'tipos de riesgo',
                'ordering': ['nombre'],
            },
        ),
    ]
