# Generated by Django 6.1.1 on 2026-10-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_comunicadoimagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComunicadoImagen',
        ),
    ]
