# Generated by Django 6.1.1 on 2026-10-01 01:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo_barrio', models.IntegerField(blank=True, null=True)),
                ('cuadrante', models.IntegerField(blank=True, null=True)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zonas',
                'ordering': ['nombre'],
            },
        ),
    ]
